//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraafikVesipiip.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraafikVesipiip.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:MMMM yyyy}.
        /// </summary>
        public static string MonthFormat {
            get {
                return ResourceManager.GetString("MonthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kalender.
        /// </summary>
        public static string Title_Calendar {
            get {
                return ResourceManager.GetString("Title_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E.
        /// </summary>
        public static string Week_E {
            get {
                return ResourceManager.GetString("Week_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на K.
        /// </summary>
        public static string Week_K {
            get {
                return ResourceManager.GetString("Week_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на L.
        /// </summary>
        public static string Week_L {
            get {
                return ResourceManager.GetString("Week_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N.
        /// </summary>
        public static string Week_N {
            get {
                return ResourceManager.GetString("Week_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на P.
        /// </summary>
        public static string Week_P {
            get {
                return ResourceManager.GetString("Week_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R.
        /// </summary>
        public static string Week_R {
            get {
                return ResourceManager.GetString("Week_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на T.
        /// </summary>
        public static string Week_T {
            get {
                return ResourceManager.GetString("Week_T", resourceCulture);
            }
        }
    }
}
